{% set name = "rpaframework-pdf" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rpaframework-pdf-{{ version }}.tar.gz
  sha256: 2325274cc5d3ddb4d085ab6b532b0faad24dbce077a6510eaa1987a507d40a94

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - fpdf2 >=2.3.0,<3.0.0
    - pdfminer.six ==20201018
    - pypdf2 >=1.26.0,<2.0.0
    - python >=3.6,<4.0
    - robotframework >=3.2.2,<5.0
    - robotframework-pythonlibcore >=2.1.0,<3.0.0
    - rpaframework-core >=6.1.0,<7.0.0
    - sortedcontainers >=1

test:
  imports:
    - RPA
    - RPA.PDF
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://rpaframework.org/
  summary: PDF library of RPA Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
