{% set name = "rpaframework-pdf" %}
{% set version = "7.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rpaframework_pdf-{{ version }}.tar.gz
  sha256: 403d83246828e9836a7bc695a3e0cfb8843b3345453ca8369901ab92d389e698

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - rpaframework-core >=11.0.0,<12.0.0
    - robotframework >=4.0.0,!=4.0.1,!=6.1.0,<7.0.0
    - robotframework-pythonlibcore >=4.2.0,<5.0.0
    - pdfminer.six 20221105
    - pypdf >=3.15.0,<4.0.0
    - fpdf2 >=2.7.3,<3.0.0

test:
  imports:
    - RPA
    - RPA.PDF
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://rpaframework.org/
  summary: PDF library of RPA Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
